In [1]:
import os                               # Operating system
import math                             # Mathematics
import numpy as np                      # Arrays
import pandas as pd                     # Dataframes
import matplotlib.pyplot as plt         # Graphs
from matplotlib import cm               # Colours
import scipy                            # Scientific computing

In [2]:
stocks = [stock.split('.')[0] for stock in sorted(os.listdir('archive'))]

In [3]:
print(stocks)

['A2M', 'AGL', 'ALL', 'ALQ', 'ALU', 'ALX', 'AMC', 'AMP', 'ANN', 'ANZ', 'APA', 'APT', 'AST', 'ASX', 'AWC', 'AZJ', 'BEN', 'BHP', 'BLD', 'BOQ', 'BPT', 'BSL', 'BXB', 'CAR', 'CBA', 'CCL', 'CGF', 'CHC', 'CIM', 'COH', 'COL', 'CPU', 'CSL', 'CTX', 'CWN', 'CWY', 'DMP', 'DOW', 'DXS', 'EVN', 'FBU', 'FLT', 'FMG', 'FPH', 'GMG', 'GOZ', 'GPT', 'HVN', 'IAG', 'IEL', 'ILU', 'IPL', 'JBH', 'JHX', 'LLC', 'MFG', 'MGR', 'MPL', 'MQG', 'NAB', 'NCM', 'NST', 'ORG', 'ORI', 'OSH', 'QAN', 'QBE', 'QUB', 'REA', 'RHC', 'RIO', 'RMD', 'S32', 'SAR', 'SCG', 'SEK', 'SGP', 'SGR', 'SHL', 'SKI', 'SOL', 'SPK', 'STO', 'SUN', 'SVW', 'SYD', 'TAH', 'TCL', 'TLS', 'TPM', 'TWE', 'VCX', 'VEA', 'WBC', 'WES', 'WOR', 'WOW', 'WPL', 'WTC', 'XRO']


In [4]:
len(stocks)

100

In [5]:
ex_stock = pd.read_csv('archive/A2M.csv')

In [6]:
ex_stock.head()

Date   Open   High    Low  Close  Adj Close   Volume
0  2015-03-31  0.555  0.595  0.530  0.565      0.565  4816294
1  2015-04-01  0.575  0.580  0.555  0.565      0.565  4376660
2  2015-04-02  0.560  0.565  0.535  0.555      0.555  2779640
3  2015-04-07  0.545  0.550  0.540  0.545      0.545   392179
4  2015-04-08  0.545  0.545  0.530  0.540      0.540   668446

In [7]:
ex_stock.tail()

Date       Open       High        Low      Close  Adj Close  \
1264  2020-03-26  16.000000  16.490000  15.720000  16.000000  16.000000   
1265  2020-03-27  16.570000  16.650000  15.870000  15.870000  15.870000   
1266  2020-03-30  15.660000  16.879999  15.660000  16.879999  16.879999   
1267  2020-03-31  16.950001  17.040001  16.379999  16.600000  16.600000   
1268  2020-04-01  16.600000  16.990000  16.570000  16.820000  16.820000   

       Volume  
1264  4336588  
1265  4379370  
1266  3398048  
1267  4370583  
1268  4046347

In [8]:
ex_stock.describe()

Open         High          Low        Close    Adj Close  \
count  1269.000000  1269.000000  1269.000000  1269.000000  1269.000000   
mean      6.879588     6.988677     6.779320     6.884976     6.884976   
std       5.368422     5.450933     5.298240     5.377636     5.377636   
min       0.470000     0.475000     0.455000     0.465000     0.465000   
25%       1.760000     1.795000     1.735000     1.765000     1.765000   
50%       5.920000     6.040000     5.880000     5.990000     5.990000   
75%      12.000000    12.160000    11.830000    11.990000    11.990000   
max      17.200001    17.299999    17.030001    17.129999    17.129999   

             Volume  
count  1.269000e+03  
mean   4.798958e+06  
std    5.239342e+06  
min    0.000000e+00  
25%    2.239971e+06  
50%    3.530877e+06  
75%    5.355630e+06  
max    6.139730e+07

In [9]:
ex_stock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1269 entries, 0 to 1268
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       1269 non-null   object 
 1   Open       1269 non-null   float64
 2   High       1269 non-null   float64
 3   Low        1269 non-null   float64
 4   Close      1269 non-null   float64
 5   Adj Close  1269 non-null   float64
 6   Volume     1269 non-null   int64  
dtypes: float64(5), int64(1), object(1)
memory usage: 69.5+ KB


In [10]:
dates = pd.date_range('2000-01-01', '2020-03-31')
data = pd.DataFrame({'Time': dates})

In [11]:
for s in stocks:
    price = pd.read_csv('archive/' + s + '.csv', usecols=['Date', 'Adj Close']) #read file csv
    
    price['Date'] = pd.to_datetime(price['Date']) #Typecast date
    
    price.rename(columns={"Date": "Time", "Adj Close": s}, inplace=True) #rename column
    
    data = pd.merge(data, price, how='left', on=['Time'], sort=False) #merge table

In [12]:
data.head()

Time  A2M       AGL       ALL       ALQ       ALU  ALX       AMC  \
0 2000-01-01  NaN       NaN       NaN       NaN       NaN  NaN       NaN   
1 2000-01-02  NaN       NaN       NaN       NaN       NaN  NaN       NaN   
2 2000-01-03  NaN       NaN       NaN       NaN       NaN  NaN       NaN   
3 2000-01-04  NaN  4.665331  2.925006  0.018139  3.357754  NaN  1.461500   
4 2000-01-05  NaN  4.606756  2.768106  0.017776  3.147893  NaN  1.440916   

        AMP       ANN  ...  TWE  VCX  VEA       WBC       WES  WOR       WOW  \
0       NaN       NaN  ...  NaN  NaN  NaN       NaN       NaN  NaN       NaN   
1       NaN       NaN  ...  NaN  NaN  NaN       NaN       NaN  NaN       NaN   
2  5.601532       NaN  ...  NaN  NaN  NaN       NaN       NaN  NaN       NaN   
3  5.422170  7.067056  ...  NaN  NaN  NaN  3.419256  2.086992  NaN  2.457825   
4  5.192115  6.968902  ...  NaN  NaN  NaN  3.356248  2.061686  NaN  2.448280   

        WPL  WTC  XRO  
0       NaN  NaN  NaN  
1       NaN  NaN  NaN  
2       NaN  NaN  NaN  
3  5.309288  NaN  NaN  
4  5.267546  NaN  NaN  

[5 rows x 101 columns]

In [13]:
data['Time'].dt.weekday

0       5
1       6
2       0
3       1
4       2
       ..
7391    4
7392    5
7393    6
7394    0
7395    1
Name: Time, Length: 7396, dtype: int64

In [14]:
data = data[data['Time'].dt.weekday < 5]

In [15]:
data.head()

Time  A2M       AGL       ALL       ALQ       ALU  ALX       AMC  \
2 2000-01-03  NaN       NaN       NaN       NaN       NaN  NaN       NaN   
3 2000-01-04  NaN  4.665331  2.925006  0.018139  3.357754  NaN  1.461500   
4 2000-01-05  NaN  4.606756  2.768106  0.017776  3.147893  NaN  1.440916   
5 2000-01-06  NaN  4.535735  2.690722  0.017414  3.183872  NaN  1.428563   
6 2000-01-07  NaN  4.654961  2.726219  0.017776  3.117912  NaN  1.451209   

        AMP       ANN  ...  TWE  VCX  VEA       WBC       WES  WOR       WOW  \
2  5.601532       NaN  ...  NaN  NaN  NaN       NaN       NaN  NaN       NaN   
3  5.422170  7.067056  ...  NaN  NaN  NaN  3.419256  2.086992  NaN  2.457825   
4  5.192115  6.968902  ...  NaN  NaN  NaN  3.356248  2.061686  NaN  2.448280   
5  5.045533  6.772593  ...  NaN  NaN  NaN  3.349603  2.063373  NaN  2.443507   
6  5.264914  6.739878  ...  NaN  NaN  NaN  3.349603  2.068435  NaN  2.424422   

        WPL  WTC  XRO  
2       NaN  NaN  NaN  
3  5.309288  NaN  NaN  
4  5.267546  NaN  NaN  
5  5.147910  NaN  NaN  
6  5.229499  NaN  NaN  

[5 rows x 101 columns]

In [16]:
data = data.dropna(axis=0, how='all')

In [17]:
data.head()

Time  A2M       AGL       ALL       ALQ       ALU  ALX       AMC  \
2 2000-01-03  NaN       NaN       NaN       NaN       NaN  NaN       NaN   
3 2000-01-04  NaN  4.665331  2.925006  0.018139  3.357754  NaN  1.461500   
4 2000-01-05  NaN  4.606756  2.768106  0.017776  3.147893  NaN  1.440916   
5 2000-01-06  NaN  4.535735  2.690722  0.017414  3.183872  NaN  1.428563   
6 2000-01-07  NaN  4.654961  2.726219  0.017776  3.117912  NaN  1.451209   

        AMP       ANN  ...  TWE  VCX  VEA       WBC       WES  WOR       WOW  \
2  5.601532       NaN  ...  NaN  NaN  NaN       NaN       NaN  NaN       NaN   
3  5.422170  7.067056  ...  NaN  NaN  NaN  3.419256  2.086992  NaN  2.457825   
4  5.192115  6.968902  ...  NaN  NaN  NaN  3.356248  2.061686  NaN  2.448280   
5  5.045533  6.772593  ...  NaN  NaN  NaN  3.349603  2.063373  NaN  2.443507   
6  5.264914  6.739878  ...  NaN  NaN  NaN  3.349603  2.068435  NaN  2.424422   

        WPL  WTC  XRO  
2       NaN  NaN  NaN  
3  5.309288  NaN  NaN  
4  5.267546  NaN  NaN  
5  5.147910  NaN  NaN  
6  5.229499  NaN  NaN  

[5 rows x 101 columns]

In [18]:
r = data[(data['Time'].dt.weekday == 4) & (data['Time'] >= '2019-01-01')]

In [19]:
r.head()

Time    A2M        AGL        ALL       ALQ        ALU       ALX  \
6943 2019-01-04  10.10  19.018661  21.129770  6.330474  20.455803  5.747818   
6950 2019-01-11  10.71  19.488373  22.849636  6.806231  22.797544  5.984154   
6957 2019-01-18  11.75  19.248911  23.154297  6.883906  23.663399  5.917983   
6964 2019-01-25  11.66  19.948872  24.176390  7.029545  24.548929  6.154319   
6971 2019-02-01  12.21  19.856771  23.989660  7.204313  24.676842  6.343391   

            AMC       AMP        ANN  ...        TWE       VCX       VEA  \
6943  12.334577  2.378983  20.739098  ...  13.463317  2.389107  1.708126   
6950  12.493673  2.496949  21.491144  ...  14.260361  2.492572  1.736595   
6957  12.531107  2.614915  22.301039  ...  14.730905  2.464354  1.736595   
6964  12.802505  2.300339  22.561363  ...  14.884550  2.464354  1.708126   
6971  12.905449  2.202034  22.503513  ...  14.922962  2.436136  1.736595   

            WBC        WES        WOR        WOW        WPL        WTC  \
6943  23.459414  30.052795  11.137593  28.059692  29.547916  16.431517   
6950  24.003019  29.931007  12.878445  28.385300  30.797985  19.085300   
6957  24.509134  30.446253  13.070804  28.691753  31.381350  19.314766   
6964  24.256075  30.774136  13.532466  29.228050  31.742481  20.252569   
6971  23.037647  30.174578  13.570937  28.193768  31.372093  20.621704   

            XRO  
6943  40.900002  
6950  42.660000  
6957  42.130001  
6964  42.299999  
6971  43.299999  

[5 rows x 101 columns]

In [20]:
r = r.drop(['Time'], axis=1)

In [21]:
r

A2M        AGL        ALL       ALQ        ALU       ALX  \
6943  10.100000  19.018661  21.129770  6.330474  20.455803  5.747818   
6950  10.710000  19.488373  22.849636  6.806231  22.797544  5.984154   
6957  11.750000  19.248911  23.154297  6.883906  23.663399  5.917983   
6964  11.660000  19.948872  24.176390  7.029545  24.548929  6.154319   
6971  12.210000  19.856771  23.989660  7.204313  24.676842  6.343391   
...         ...        ...        ...       ...        ...       ...   
7363  15.420000  19.139999  33.110001  8.360000  30.799999  8.020000   
7370  16.389999  18.650000  31.920000  7.770000  29.690001  7.650000   
7377  15.710000  17.170000  27.910000  6.290000  27.000000  6.100000   
7384  16.170000  16.420000  17.540001  5.350000  26.219999  5.260000   
7391  15.870000  15.930000  20.170000  5.390000  26.000000  5.320000   

            AMC       AMP        ANN        ANZ  ...        TWE       VCX  \
6943  12.334577  2.378983  20.739098  22.826998  ...  13.463317  2.389107   
6950  12.493673  2.496949  21.491144  23.758904  ...  14.260361  2.492572   
6957  12.531107  2.614915  22.301039  24.540197  ...  14.730905  2.464354   
6964  12.802505  2.300339  22.561363  24.653158  ...  14.884550  2.464354   
6971  12.905449  2.202034  22.503513  23.467096  ...  14.922962  2.436136   
...         ...       ...        ...        ...  ...        ...       ...   
7363  14.248165  1.675000  29.600000  24.830000  ...  10.831618  2.160000   
7370  14.070000  1.575000  27.680000  22.139999  ...  10.000000  2.160000   
7377  11.100000  1.445000  26.879999  18.799999  ...   9.530000  1.750000   
7384  11.900000  1.310000  21.910000  16.020000  ...   9.660000  1.135000   
7391  12.540000  1.270000  23.209999  15.470000  ...   9.460000  0.965000   

           VEA        WBC        WES        WOR        WOW        WPL  \
6943  1.708126  23.459414  30.052795  11.137593  28.059692  29.547916   
6950  1.736595  24.003019  29.931007  12.878445  28.385300  30.797985   
6957  1.736595  24.509134  30.446253  13.070804  28.691753  31.381350   
6964  1.708126  24.256075  30.774136  13.532466  29.228050  31.742481   
6971  1.736595  23.037647  30.174578  13.570937  28.193768  31.372093   
...        ...        ...        ...        ...        ...        ...   
7363  1.721867  23.639999  40.650002  12.520000  38.330315  27.920000   
7370  1.648492  21.350000  39.200001  11.770000  38.000000  26.379999   
7377  1.526200  18.120001  37.849998   9.610000  37.049999  20.969999   
7384  1.252267  15.770000  33.279999   5.760000  37.470001  16.000000   
7391  1.225000  14.890000  32.250000   5.790000  34.799999  16.840000   

            WTC        XRO  
6943  16.431517  40.900002  
6950  19.085300  42.660000  
6957  19.314766  42.130001  
6964  20.252569  42.299999  
6971  20.621704  43.299999  
...         ...        ...  
7363  15.083417  73.650002  
7370  15.030000  75.169998  
7377  13.610000  80.389999  
7384  11.800000  61.750000  
7391  14.500000  65.199997  

[65 rows x 100 columns]

In [22]:
r = r.pct_change(fill_method='ffill')

In [23]:
r.head()

A2M       AGL       ALL       ALQ       ALU       ALX       AMC  \
6943       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
6950  0.060396  0.024697  0.081395  0.075153  0.114478  0.041118  0.012898   
6957  0.097106 -0.012287  0.013333  0.011412  0.037980 -0.011058  0.002996   
6964 -0.007660  0.036364  0.044143  0.021156  0.037422  0.039935  0.021658   
6971  0.047170 -0.004617 -0.007724  0.024862  0.005211  0.030722  0.008041   

           AMP       ANN       ANZ  ...       TWE       VCX       VEA  \
6943       NaN       NaN       NaN  ...       NaN       NaN       NaN   
6950  0.049587  0.036262  0.040825  ...  0.059201  0.043307  0.016667   
6957  0.047244  0.037685  0.032884  ...  0.032997 -0.011321  0.000000   
6964 -0.120301  0.011673  0.004603  ...  0.010430  0.000000 -0.016394   
6971 -0.042735 -0.002564 -0.048110  ...  0.002581 -0.011450  0.016667   

           WBC       WES       WOR       WOW       WPL       WTC       XRO  
6943       NaN       NaN       NaN       NaN       NaN       NaN       NaN  
6950  0.023172 -0.004052  0.156304  0.011604  0.042307  0.161506  0.043032  
6957  0.021085  0.017214  0.014937  0.010796  0.018942  0.012023 -0.012424  
6964 -0.010325  0.010769  0.035320  0.018692  0.011508  0.048554  0.004035  
6971 -0.050232 -0.019483  0.002843 -0.035387 -0.011669  0.018227  0.023641  

[5 rows x 100 columns]

In [24]:
p = data.drop(['Time'],axis=1).tail(1).to_numpy()

In [25]:
p

array([[ 16.6     ,  17.190001,  21.35    ,   5.56    ,  28.59    ,
          5.51    ,  13.04    ,   1.335   ,  27.190001,  16.959999,
         10.26    ,  18.799999,   1.71    ,  77.089996,   1.46    ,
          4.23    ,   6.27    ,  28.98    ,   2.05    ,   5.      ,
          1.15    ,   8.63    ,  10.56    ,  11.75    ,  61.82    ,
          8.84    ,   4.      ,   6.86    ,  23.25    , 187.449997,
         15.16    ,   9.71    , 296.679993,  22.32    ,   7.6     ,
          1.695   ,  51.099998,   2.98    ,   9.09    ,   3.82    ,
          3.24    ,   9.91    ,  10.      ,  28.84    ,  12.1     ,
          2.52    ,   3.63    ,   2.830808,   6.2     ,  11.56    ,
          6.98    ,   2.02    ,  28.      ,  18.52    ,  10.3     ,
         43.52    ,   2.09    ,   2.66    ,  85.75    ,  16.68    ,
         23.049999,  10.53    ,   4.38    ,  15.35    ,   2.38    ,
          3.23    ,   8.6     ,   2.15    ,  76.989998,  57.279999,
         84.57    ,  24.690001,   1.765   ,   3.

In [26]:
sigma = r.cov().to_numpy()

In [27]:
sigma.shape

(100, 100)

In [158]:
mu = r.mean().to_numpy()

In [29]:
mu.shape

(100,)

In [30]:
import cvxpy as cp 

In [31]:
n = len(stocks)

In [32]:
x = cp.Variable(shape=n, integer=True)
threshold = cp.Parameter(nonneg=True) # maximum portfolio variance
k = cp.Parameter(nonneg=True) # maximum allocation into one stock

In [33]:
x

Variable((100,), integer=True)

In [34]:
threshold

Parameter((), nonneg=True)

In [35]:
k

Parameter((), nonneg=True)

In [36]:
mean = mu.T@x
variance = cp.quad_form(x, sigma)

In [37]:
mean

Expression(AFFINE, UNKNOWN, ())

In [38]:
variance

Expression(AFFINE, ZERO, (1, 1))

In [59]:
'{0:07b}'.format(1)

'0000001'

In [40]:
ri = np.random.randint(50, size=100)

In [41]:
sum(ri * p[0] > 3000)

2

In [47]:
3000 / np.max(p)

10.111905321502416

In [63]:
x = np.random.randint(100, size=100)
x_dna = '' 
for i in x:
    x_dna += '{0:07b}'.format(i)

In [64]:
x_dna

'1011111101001000101001010010100100010010100100110001001000110100111010100110010101010111011110001000111110110110000101010011111011011100100011000100111010100010010110101001011011100000000100101111000000110100010101010100110001011110001000001100110000110110111101101110111111100001011101101100011010111010001000100101011110010000110010000001011010111110110011001000001101100000010101001011000010111101000000011111000110111000001010000110100010110010001101000111100010111100100110101111011010011110001110011011110011111100000101011001001000100010111010100101111010011000010001010000100010010001100001100110001010100110101100100000001010010110000001011010110001011110110011111001110101010011000010110110'

In [104]:
x

array([95, 82, 20, 82, 72, 74, 38, 18, 26, 58, 76, 85, 59, 98, 31, 54, 10,
       79, 91, 72, 98, 58, 68, 90, 75, 56,  2, 47,  1, 81, 42, 76, 47,  8,
       25, 67, 55, 91, 95, 97, 59, 49, 87, 34, 18, 94, 33, 72, 11, 47, 89,
       72, 27,  1, 41, 48, 94, 64, 62, 27, 65, 33, 81, 50, 26, 30, 23, 73,
       87, 90, 60, 57, 94, 63,  2, 89, 17, 11, 84, 94, 76, 17, 33,  9, 12,
       25, 69, 38, 89,  0, 82, 96, 45, 49, 61, 79, 78, 84, 97, 54])

In [214]:
def gen_pop(n):
    pop = []
    for _ in range(n):
        x = np.random.randint(100, size=100)
        x_dna = '' 
        for i in x:
            x_dna += '{0:07b}'.format(i)
        pop.append(x_dna)
    return pop

In [73]:
a = gen_pop(3)

In [66]:
len(x_dna)

700

In [70]:
np.random.randint(0,100)

11

In [74]:
k = '111000'
k[:3] + k[3:]

'111000'

In [87]:
i = np.random.randint(6)
j = k[i]
if j=='1':
    c = k[:i] + '0' + k[i+1:]
else:
    c = k[:i] + '1' + k[i+1:]
print(c)

011000


In [75]:
def xover(p1, p2):
    cross_point = np.random.randint(0, len(p1))
    
    child1 = p1[:cross_point] + p2[cross_point:]
    child2 = p2[:cross_point] + p1[cross_point:]
    
    return child1, child2

In [79]:
a[0][1]

'1000101010001100001001010111001001000111000111100010001011000110010000011111100000110010000011001100011001000110101001010100011100011001011110001110010010101010001110100111111000010101101000100000001001110011100111000101000101110011011111000111100110010100110100101001001010001010101000000100000010101100011110001110010110101110110011010110010100100000111010110010100110000101111000011100110110110011000110000111101010010001011000010010100000011010100100110000110001000101000000001100000100001101001011110100110000010000101011011111010001000001101000001000010000001100100001100011000100110000101000010101110111001100001001101100001011011011010000111100110001001101101011110110000001000000011010000100'

In [80]:
a[1][1]

'1011001010001110101011000111101101110001000110100100001010001100110111100011011000010011001100001101011101000100001111100101101000010110000000010011100011101001100110000000100010001100111100100011100011100100111011100101000110011111001100101101100100110100001001000100001110000110000110001100011100010100001001101110110110000010100111011010000000111101111110011001100001111000011001111000100101000100001010110000110110001010111101100100101100111010010000101011010110001101111010101011011101100111110001110100100000110011000100110011100110001101101000100011000000110111010110010010000110000101110000011000110101001010101001100101010010001010000001110110111100011000101000010101001010011010101011010000'

In [81]:
p1, p2 = a[0][1], a[1][1]

In [83]:
child1, child2 = xover(p1, p2)

In [85]:
len(child1)

700

In [91]:
def mutate(child):
    i = np.random.randint(len(child))
    j = child[i]
    
    if j=='1':
        mu = child[:i] + '0' + child[i+1:]
    else:
        mu = child[:i] + '1' + child[i+1:]
    return mu

In [92]:
mutate(child1)

'1000101010001100001001010111001001000111000111100010001011000110010000011111100000110010000011001100011001000110101001010100011100011001011110001110010010101010001110100111111000010101101000100000001001110011100111000101000101110011011111000111100110010100110100101001001010001010101000000100000010101100011110001110010110101110110011010110000100100000111010110010100110000101111000011100110110110011000110000111101010010001011000010010100000011010100100110000110001000101000000001100000100001101001011110100110000010000101011011111010001000001101000001000010000001100100001100011000100110000110000011000110101001010101001100101010010001010000001110110111100011000101000010101001010011010101011010000'

In [187]:
def phenotype(dna):
    l = [dna[i * 7: i * 7 + 7] for i in range(100)]
    x = [int(n,2) for n in l]
    return np.array(x)

In [188]:
ch = phenotype(child1)

In [189]:
mu.T

array([ 8.30469863e-03, -2.33732977e-03,  1.60510592e-03, -1.22766802e-03,
        5.52845527e-03, -2.66351653e-04,  1.04480461e-03, -8.05921419e-03,
        2.41983225e-03, -5.20743031e-03,  2.54810736e-03,  1.54214315e-02,
        2.48306325e-03,  3.83772337e-03, -3.58330223e-03,  2.40736606e-03,
       -6.48272739e-03, -1.63289704e-04, -9.94063973e-03, -8.79919168e-03,
       -1.17241600e-03, -2.84729788e-03,  1.68224541e-03,  3.07399379e-03,
       -1.60489118e-03,  1.06570156e-03, -9.42085327e-03, -3.71579288e-05,
       -8.65422830e-03,  8.84344524e-04,  5.50671321e-03, -7.86074968e-03,
        6.94428886e-03, -1.86780334e-04, -5.08055421e-03,  2.00780208e-03,
        4.65096697e-03, -1.03238352e-02, -1.56010426e-03,  1.92319671e-03,
       -4.07768765e-03, -1.62718321e-02,  1.76289567e-02,  1.31226305e-02,
        1.69648114e-03, -4.20045173e-03, -5.15336348e-03,  1.53720142e-03,
       -1.41934114e-03,  6.43516482e-03,  6.13096691e-04, -7.23822481e-03,
        5.04139233e-03,  

In [190]:
mu.T.dot(ch)

-2.774194052096007

In [191]:
ch.shape

(100,)

In [193]:
ch.T.dot(sigma).dot(ch)

21808.37018364914

In [194]:
mu.shape

(100,)

In [195]:
ch.shape

(100,)

In [206]:
p

array([[ 16.6     ,  17.190001,  21.35    ,   5.56    ,  28.59    ,
          5.51    ,  13.04    ,   1.335   ,  27.190001,  16.959999,
         10.26    ,  18.799999,   1.71    ,  77.089996,   1.46    ,
          4.23    ,   6.27    ,  28.98    ,   2.05    ,   5.      ,
          1.15    ,   8.63    ,  10.56    ,  11.75    ,  61.82    ,
          8.84    ,   4.      ,   6.86    ,  23.25    , 187.449997,
         15.16    ,   9.71    , 296.679993,  22.32    ,   7.6     ,
          1.695   ,  51.099998,   2.98    ,   9.09    ,   3.82    ,
          3.24    ,   9.91    ,  10.      ,  28.84    ,  12.1     ,
          2.52    ,   3.63    ,   2.830808,   6.2     ,  11.56    ,
          6.98    ,   2.02    ,  28.      ,  18.52    ,  10.3     ,
         43.52    ,   2.09    ,   2.66    ,  85.75    ,  16.68    ,
         23.049999,  10.53    ,   4.38    ,  15.35    ,   2.38    ,
          3.23    ,   8.6     ,   2.15    ,  76.989998,  57.279999,
         84.57    ,  24.690001,   1.765   ,   3.

In [196]:
sum(abs(mu[np.where(p[0]*ch > 3000)]))

0.03300608585795514

In [123]:
def evaluate(dna, mu, sigma, k, p):
    x = phenotype(dna)
    mean = mu.T.dot(x) 
    penalty = sum(abs(mu[np.where(p[0]*x > k)]))
    variance = 0.5 * x.T.dot(sigma).dot(x)
    
    return mean, 1 / variance, penalty

In [209]:
vars()['a'] = 10

In [215]:
population = gen_pop(10)

In [218]:
phenotype(population[0])

array([14,  7, 75, 48, 92,  2, 93, 40, 79, 73, 31, 82, 19, 33, 35, 94, 28,
        6, 30, 42, 47, 12, 46,  2, 32, 36, 32, 54,  4, 82, 74, 67,  3, 23,
       89, 76, 20, 59, 79, 66, 56, 68, 48,  9, 18, 93, 94, 48, 19, 39, 83,
       37, 54, 22, 45, 94, 51, 87, 71, 67,  2, 34, 17, 15, 42, 69, 21, 12,
       20, 77, 75,  4, 93,  8, 76, 55,  6, 85, 53, 46, 76, 14, 23, 83,  9,
       26, 64, 45, 73,  4, 67, 12, 67, 78, 54,  2, 90,  4, 61, 39])

In [319]:
def is_pareto_efficient_simple(costs):
    """
    Find the pareto-efficient points
    :param costs: An (n_points, n_costs) array
    :return: A (n_points, ) boolean array, indicating whether each point is Pareto efficient
    """
    is_efficient = np.ones(costs.shape[0], dtype = bool)
    for i, c in enumerate(costs):
        if is_efficient[i]:
            is_efficient[is_efficient] = np.any(costs[is_efficient] > c, axis=1)  # Keep any point with a lower cost
            is_efficient[i] = True  # And keep self
    return is_efficient

In [320]:
C = [[0.3296170319979843, 0.0, 0.44472108843537406], [0.3296170319979843,0.0, 0.44472108843537406], [0.32920760896951373, 0.0, 0.4440408163265306], [0.32920760896951373, 0.0, 0.4440408163265306], [0.33815192743764166, 0.0, 0.44356462585034007]]

In [321]:
C = np.array(Cost)

In [322]:
l = []
cost = C
index = np.arange(len(cost))
while len(cost) > 0:
    b = is_pareto_efficient_simple(cost)
    l += index[b].tolist()
    index = index[b == 0]
    cost = cost[b == 0]

In [323]:
C[l]

array([[0.32961703, 0.        , 0.44472109],
       [0.33815193, 0.        , 0.44356463],
       [0.32961703, 0.        , 0.44472109],
       [0.32920761, 0.        , 0.44404082],
       [0.32920761, 0.        , 0.44404082]])

In [324]:
def sorted_index(C):
    l = []
    cost = C
    index = np.arange(len(cost))
    while len(cost) > 0:
        b = is_pareto_efficient_simple(cost)
        l += index[b].tolist()
        index = index[b == 0]
        cost = cost[b == 0]
    
    return l

In [325]:
sorted_index(C)

[0, 4, 1, 2, 3]

In [332]:
a = np.array(C[l][0])
b = np.array(C[l][1])
c = np.array(C[l][-1])

In [333]:
a>b

array([False, False,  True])

In [334]:
a>c

array([ True, False,  True])

In [351]:
def fight(p1, p2):
    l = np.array([p1, p2])
    i = is_pareto_efficient_simple(l)
    print(i)
    return l[i][0].tolist()

In [352]:
a = [0.32961703, 0.        , 0.44472109]
c = [0.32920761, 0.        , 0.44404082]
b = a
fight(c, b)

[False  True]


[0.32961703, 0.0, 0.44472109]

In [354]:
np.array([[1], [2]])[[True, False]]

array([[1]])

In [355]:
p = ['a', 'b']
e = [a, b]

In [360]:
def fight(parents, evaluates):
    l = np.array(evaluates)
    i = is_pareto_efficient_simple(l)
    
    return np.array(parents)[i][0].tolist()

In [361]:
fight(p, e)

'a'

In [368]:
import numpy as np

def pareto_frontier_multi(myArray):
    # Sort on first dimension
    myArray = myArray[myArray[:,0].argsort()]
    # Add first row to pareto_frontier
    pareto_frontier = myArray[0:1,:]
    # Test next row against the last row in pareto_frontier
    for row in myArray[1:,:]:
        if sum([row[x] >= pareto_frontier[-1][x]
                for x in range(len(row))]) == len(row):
            # If it is better on all features add the row to pareto_frontier
            pareto_frontier = np.concatenate((pareto_frontier, [row]))
    return pareto_frontier

def test():
    myArray = np.array([[1,1,1],[2,2,2],[4,4,4],[3,3,3]])
    print( pareto_frontier_multi(myArray))

test()

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
